import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import '../public/fonts/stylesheet.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SK Entertainment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className='relative'>
        <Navbar />
          {children}
        
        <Footer />
      </body>
    </html>
  );
}
